### ISSUE TITLE
Wrong label value when value is less than 1

### ISSUE THREAD

**Issue by r1n1os** [NicosNicolaou16/percentages_with_animation#4]
Using the **LinearPercentage** I noticed that in case where I have a

 value which is less than 1 (i.e 0.50) the bar is filled with the percentage I'm passing to the widget however, the label shows 0. 

        LinearPercentage(
                currentPercentage: 0.50,
                maxPercentage: 10,
                backgroundHeight: 20,
                percentageHeight: 20,
                leftRightText: LeftRightText.leftOnly,
                showPercentageOnPercentageView: false,
                percentageOnPercentageViewTextStyle: const TextStyle(color: Colors.white),
                             backgroundDecoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(10),
                  color: Colors.black38,
                ),
                percentageDecoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(10),
                  color: pokemonStatsColor,
                ),
              ),

### Example Result
<img src="https://github.com/NicosNicolaou16/percentages_with_animation/assets/32699540/95fed6f5-47c4-43aa-ad57-99b26b71c18d" width="200">

If you need any extra information let me know.

**Comment by NicosNicolaou16** [comment]
Hello @r1n1os, this is not an issue/bug, the library is working like this, the output on the view, it accepts only integer values and not decimal! Maybe this is a future feature.

**Comment by r1n1os** [comment]
Oh sorry you are correct I missed this part in your read me file. 

It would be a good improvement for your library.

Also, until you do this maybe is a good idea to also add an assertion!

Thank you!

**Comment by NicosNicolaou16** [comment]
This enhancement will be available on the next version!
Thank you very much for your feedback!

**Comment by NicosNicolaou16** [comment]
Hello @r1n1os, You can check the version 0.0.9. Thank you again for your support and for your feedback.
